accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.loginview,name='login'),
    path('register/',views.register,name='register'),
]

chat/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('',views.index,name='index'),
    path('getChats/<int:id>',views.getChats,name='getChats'),
    path('getMessages/',views.getMessages,name='getMessages'),
    path('chatting/<int:id>',views.chatting,name='chatting'),
    path('send/',views.send,name='send'),
    path('getContacts/',views.getContacts,name='getContacts')
]

chatapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('',include('chat.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Chat(models.Model):
    user1 = models.ForeignKey(User,related_name='chats1',on_delete=models.CASCADE)
    user2 = models.ForeignKey(User,related_name='chats2',on_delete=models.CASCADE)
    
class Message(models.Model):
    
    messageText = models.TextField()
    # messageFile = models.FileField(upload_to='files/',null=True,blank=True,)
    # messageImage = models.ImageField(upload_to='images/',null=True,blank=True)
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='sent_messages')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE,related_name='received_messages')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User




class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control',}),
            'password1':forms.PasswordInput(attrs={'class':'form-control',}),
            'password2':forms.PasswordInput(attrs={'class':'form-control',})
        }

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate





# Create your views here.



def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if form.is_valid():
            if password1==password2:
                form.save()
                return redirect('accounts:login')
            # else:
            #     raise ValidationError('Password doesn\'t match')
    return render(request,'accounts/register.html',{'form':form})


def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('chat:index')
    return render(request,'accounts/login.html')

chat/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from .models import Message,Chat
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.


def chatting(request,id):
    other_user = get_object_or_404(User,id=id)
    if not Chat.objects.filter(Q(user1=request.user,user2=other_user)| Q(user2=request.user,user1=other_user)).exists():
        create_chat(request,id)
    context={
        'other_user':other_user,
        'this_user':request.user,
        'id':request.user.id
    }
    return render(request,'chat/history.html',context)

    


def send(request):
    senderid = request.POST['sender']
    receiverid = request.POST['receiver']
    sender = get_object_or_404(User,id=senderid)
    receiver = get_object_or_404(User,id=receiverid)
    message = request.POST['message']
    print(senderid,receiverid,message)
    msg = Message.objects.create(sender=sender,receiver=receiver,messageText=message)
    msg.save()



def getChats(request,id):
    users = []

    user = get_object_or_404(User,id=id)
    chats = Chat.objects.filter(user1=user)
    for chat in chats:
        users.append(chat.user2)

    chats = Chat.objects.filter(user2=user)
    for chat in chats:
        users.append(chat.user1)
   
    users_list = [
        {'user_id':user.id,
        'username':user.username}
        for user in users
    ]
    return JsonResponse({'users':users_list})

def getContacts(request):
    query = request.GET.get('q')
    users = User.objects.filter(username__icontains=query).exclude(id=request.user.id)
    users_list = [
        {'user_id':user.id,
        'username':user.username}
        for user in users
    ]
    return JsonResponse({'users':users_list})


def getMessages(request):
    id = request.GET.get('id')
    user = request.user
    other_user = get_object_or_404(User,id=id)
    messages = Message.objects.filter(Q(sender=user,receiver=other_user)|Q(sender=other_user,receiver=user))
    messages_list = [
        {
            'messageText':message.messageText,
            'sent':message.sender==user,
        }for message in messages
    ]
    return JsonResponse({'messages':messages_list})


@login_required
def index(request):

    context ={
        'id':request.user.id
        # 'users':users
    }
    return render(request,'chat/base.html',context)


def create_chat(request,id):
    user1 = request.user
    user2 = get_object_or_404(User,id=id)
    chat = Chat.objects.create(user1=user1,user2=user2)
    chat.save()

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <style>
      a{
        text-decoration: none;
      }
    </style>
</head>
<body>

    <div class="container mt-3">
      <form method="POST" >
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputUsername">Username</label>
          <input type="text" class="form-control" id="id_username" placeholder="Username" name="username">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="id_email" placeholder="Password" name="password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Sign in</button>
        <br><br>
        <p>Don't have an account? <a href="{% url 'accounts:register' %}">Register</a></p>
      </form>     
    </div>

</body>

templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <style>
      a{
        text-decoration: none;
      }
    </style>
</head>
<body>
    <div class="container mt-3">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputUsername">Username</label>
            <input type="text" class="form-control" id="id_username" placeholder="Username" name="username">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputEmail">Email address</label>
          <input type="email" class="form-control" id="id_email" placeholder="Enter email" name="email">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="id_password1" placeholder="Password" name="password1">
        </div>
        <br>
        <div class="form-group">
            <label for="exampleInputPassword2">Repeat Password</label>
            <input type="password" class="form-control" id="id_password1" placeholder="Password again" name="password2">
          </div>
          <br>  
        <button type="submit" class="btn btn-primary">Sign up</button>
        <br>
        <p>Already have an account? <a href="{% url 'accounts:login' %}">Sign in</a></p>
    </form>
    </div>
</body>
</html>

templates/chat/base.html
{% load static %}
<!DOCTYPE html> <html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>


<body>

    <main class="content">
        <div class="container p-0">
    
            <h1 class="h3 mb-3">Messages</h1>
    
            <div class="card">
                <div class="row g-0">
                    <div class="col-12 col-lg-5 col-xl-3 border-right" id="contacts-list">
    
                        <div class="px-4 d-none d-md-block">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">
                                    <input type="text" class="form-control my-3" placeholder="Search..." id="search">
                                </div>
                            </div>
                        </div>
                        <span id="contacts">

                        </span>
                        
                       
                            
                        <input type="text" id="flag" hidden value="0">
                        <hr class="d-block d-lg-none mt-1 mb-0">
                    </div>

                    {% block content %}
                    {% endblock %}
                    
                </div>
            </div>
        </div>
    </main>






    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <script>

document.getElementById('search').addEventListener('keyup',function(){
    if($('#search').val()==''){
        console.log("empty")
        document.getElementById('flag').value = '0';
    }
    else{
        document.getElementById('flag').value = '1'
        console.log($('#search').val())
    }
    myUrl = '/getContacts/?q='+$('#search').val();
    $.ajax({
        type:'GET',
        url: myUrl,
        success:function(response){
            $("#contacts").empty();
            mycontacts ="";
            for (var key in response.users) {

                var temp = `<a href="/chatting/${response.users[key].user_id}" class="list-group-item list-group-item-action border-0">
                            
                            <div class="d-flex align-items-start">
                                <img src="https://icon-library.com/images/avatar-icon-images/avatar-icon-images-4.jpg" class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
                                <div class="flex-grow-1 ml-3">` + response.users[key].username + `<div class="small"><span class="fas fa-circle chat-online"></span> Online</div>
                                </div>
                            </div>
                        </a>`
                        
                        mycontacts = mycontacts+temp;
        }
        let foot = `<hr class="d-block d-lg-none mt-1 mb-0">`
                    mycontacts = mycontacts+foot;
                     $("#contacts").append(mycontacts);
    },
    });


})

$(document).ready(function () {
        setInterval(function () {
            if($('#flag').val()==1){
                return;
            }
            $.ajax({
                type: 'GET',
                url: "{% url 'chat:getChats' id %}",
                success: function (response) {

                    $("#contacts").empty();
                    mycontacts ="";
                    
                    for (var key in response.users) {
                            var temp = `<a href="/chatting/${response.users[key].user_id}" class="list-group-item list-group-item-action border-0">
                            
                            <div class="d-flex align-items-start">
                                <img src="https://icon-library.com/images/avatar-icon-images/avatar-icon-images-4.jpg" class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
                                <div class="flex-grow-1 ml-3">` + response.users[key].username + `<div class="small"><span class="fas fa-circle chat-online"></span> Online</div>
                                </div>
                            </div>
                        </a>`
                        
                        mycontacts = mycontacts+temp;
                    }
                    let foot = `<hr class="d-block d-lg-none mt-1 mb-0">`
                    mycontacts = mycontacts+foot;
                     $("#contacts").append(mycontacts);
                },
                error: function (response) {
                    
                }
            });
        }, 1000);









        //////////////////////////////////////////////////////////////////////////////////


        setInterval(function () {
            $.ajax({
                type: 'GET',
               
                url:"/getMessages?id={{other_user.id}}",
                success: function (response) {
                    
                    $(".chat-messages").empty();
                    var chatmessages = ''
                    
                    for (var key in response.messages) {
                        let temp=''
                            if(response.messages[key].sent)
                            {
                            temp = `<div class="chat-message-right mb-4">
                                <div>
                                    <img src="https://previews.123rf.com/images/pandavector/pandavector1605/pandavector160500618/56794127-boy-avatar-ic%C3%B4ne-illustration-vectorielle-pour-la-conception-web-et-mobiles.jpg  " class="rounded-circle mr-1"
                                        alt="Chris Wood" width="40" height="40">
                                    <div class="text-muted small text-nowrap mt-2">2:43 am</div>
                                </div>
                                <div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
                                    <div class="font-weight-bold mb-1">You</div>`+
                                    response.messages[key].messageText+"</div></div>"  

                            }  
                            else{
                                temp = `<div class="chat-message-left pb-4">
                                    <div>
                                        <img src="https://cdn-icons-png.flaticon.com/512/147/147142.png" class="rounded-circle mr-1"
                                            alt="Sharon Lessman" width="40" height="40">
                                        <div class="text-muted small text-nowrap mt-2">2:42 am</div>
                                    </div>
                                    <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                                        <div class="font-weight-bold mb-1">{{other_user.username}}</div>`+
                                        response.messages[key].messageText+"</div></div>"
                                

                            }
                            
                            chatmessages = chatmessages+temp;
                         }
                    
                    document.querySelector(".chat-messages").innerHTML = chatmessages;
                },
                error: function (response) {
                    
                }
            });
        }, 1000);

















    })

    </script>


<script type="text/javascript">
        document.getElementById('post-form').addEventListener('click',function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '/send/',
            headers: {'X-CSRFToken': '{{ csrf_token }}'},
            data: {
                sender: "{{this_user.id}}",
                receiver: "{{other_user.id}}",
                message: $('#messageText').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function (data) {
                //alert(data)
            }
        });
        document.getElementById('messageText').value = ''
    });
</script>


</body>

templates/chat/history.html
{% extends 'chat/base.html' %}


{% block content %}
<div class="col-12 col-lg-7 col-xl-9">
    <div class="py-2 px-4 border-bottom d-none d-lg-block">
        <div class="d-flex align-items-center py-1">
            <div class="position-relative">
                <img src="https://cdn-icons-png.flaticon.com/512/147/147142.png" class="rounded-circle mr-1"
                    alt="Sharon Lessman" width="40" height="40">
            </div>
            <div class="flex-grow-1 pl-3">
                <strong>{{other_user.username}}</strong>
                <div class="text-muted small"><em>Typing...</em></div>
            </div>
            <div>
                <button class="btn btn-primary btn-lg mr-1 px-3"><svg xmlns="http://www.w3.org/2000/svg" width="24"
                        height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone feather-lg">
                        <path
                            d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z">
                        </path>
                    </svg></button>
                <button class="btn btn-info btn-lg mr-1 px-3 d-none d-md-inline-block"><svg
                        xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-video feather-lg">
                        <polygon points="23 7 16 12 23 17 23 7"></polygon>
                        <rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect>
                    </svg></button>
                <button class="btn btn-light border btn-lg px-3"><svg xmlns="http://www.w3.org/2000/svg" width="24"
                        height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-more-horizontal feather-lg">
                        <circle cx="12" cy="12" r="1"></circle>
                        <circle cx="19" cy="12" r="1"></circle>
                        <circle cx="5" cy="12" r="1"></circle>
                    </svg>
                </button>
            </div>
        </div>
    </div>

        <div class="position-relative">
            <div class="chat-messages p-4">
                <!-- <div class="chat-message-left pb-4">
                    <div>
                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" class="rounded-circle mr-1"
                            alt="Sharon Lessman" width="40" height="40">
                        <div class="text-muted small text-nowrap mt-2">2:42 am</div>
                    </div>
                    <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
                        <div class="font-weight-bold mb-1">{{other_user.username}}</div>
                        Sed pulvinar, massa vitae interdum pulvinar, risus lectus porttitor magna, vitae commodo lectus
                        mauris et velit.
                        Proin ultricies placerat imperdiet. Morbi varius quam ac venenatis tempus.
                    </div>
                </div> -->

                <!-- <div class="chat-message-right mb-4">
                    <div>
                        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="rounded-circle mr-1"
                            alt="Chris Wood" width="40" height="40">
                        <div class="text-muted small text-nowrap mt-2">2:43 am</div>
                    </div>
                    <div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
                        <div class="font-weight-bold mb-1">You</div>
                        Lorem ipsum dolor sit amet, vis erat denique in, dicunt prodesset te vix.
                    </div>
                </div> -->

            </div>
        </div>

    <div class="flex-grow-0 py-3 px-4 border-top sticky-bottom">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Type your message" id="messageText">
            <button class="btn btn-primary" id="post-form">Send</button>
        </div>
    </div>

</div>


{% endblock %}